### ISSUE TITLE
[Bug]: No PV sensor, only battery sensors

### ISSUE THREAD

**Issue by AtomArne** [wlcrs/huawei_solar#331] opened 2023-03-19 18:44 UTC
### Describe the issue

Hello gents,

When i am trying to connect to my inverter from my Home Assistant on the IP: 192.168.X.X Port 502 Slave 1, only my battery sensors is showing up and the "Inverter ON/OFF".
I have tried to firmware update the inverter (SUN2000-4KTL-M1 Software: V100R001C00SPC153) yet its still an issue.

If you need anyhing please let me know.

![image](https://user-images.githubusercontent.com/20305426/226199394-a21a0178-a1c3-4dfa-8474-27f4dd45d532.png)

![image](https://user-images.githubusercontent.com/20305426/226199447-415a09d9-4768-4ce1-b937-a70e28612b08.png)

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-4KTL-M1
Inverter Firmware version: V100R001C00SPC153
SDongle present: yes (SDongleA-05 V100R001C00SPC125)
Power meter present: three phase 
Battery: LUNA2000 10kw
Battery Firmware version: V100R002C00SPC118

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-3298ef56aa0658dfecaf4726927e59c6.json.txt](https://github.com/wlcrs/huawei_solar/files/11011970/config_entry-huawei_solar-3298ef56aa0658dfecaf4726927e59c6.json.txt)

### Upload your relevant debug logs

```text
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:181
First occurred: 19:40:53 (1 occurrences)
Last logged: 19:40:53

Error unloading entry SUN2000-4KTL-M1SUN2000-5KTL-M for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 515, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 437, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!



Logger: homeassistant.setup
Source: setup.py:338
First occurred: 19:37:12 (1 occurrences)
Last logged: 19:37:12

Unable to prepare setup for platform huawei_solar.sensor: Platform not found (cannot import name 'UnitOfElectricCurrent' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment] 2023-03-19 19:45
Duplicate of #301

**Closed by wlcrs** 2023-03-19 19:45 UTC
Labels: bug
