### ISSUE TITLE
[Feature Request]: Make daily yield sensor not counting battery discharge

### ISSUE THREAD

**Issue by barksten** [wlcrs/huawei_solar#155] opened 2022-10-20 11:34 UTC
### Describe your feature request

I'm not sure if it's a bug or not but the thing is:
Sensor _Daily inverter yield_ seems to be based on _Inverter Active Power_ instead of _Inverter Input Power_.
This results in battery discharge increases the daily yield and messes up the energy graphs.

### Proper usage

- [X] I confirm that this is not a bug report

**Comment by wlcrs** [comment] 2022-10-20 11:38
Duplicate of #1

**Closed by wlcrs** 2022-10-20 11:38 UTC

**Comment by barksten** [comment] 2022-10-20 11:53
Sorry! My bad! Thanks for pointing this out.
