### ISSUE TITLE
Daily yield discounts battery charge until it discharges

### ISSUE THREAD

**Issue by joaovitoriasilva** [wlcrs/huawei_solar#32] opened 2022-02-22 11:24 UTC
### Describe your feature request

Hello,

Daily yield presents the energy that is produced and gets out of the inverter. If the energy is stored in the battery it would only count to the daily yield after the battery starts discharging. 

This affects the energy dashboard and if the battery does not discharge completely until mid night it will mess up the next day numbers. 

Can this be fixed? Could not be in the daily yield entity itself but other entity to not mess up the existing one?

Thank you.

**Comment by wlcrs** [comment] 2022-02-22 15:51
Duplicate of #1

**Closed by wlcrs** 2022-02-22 15:51 UTC
