### ISSUE TITLE
[Feature Request]: depreciation code change of constant in HA2025.9

### ISSUE THREAD

**Issue by pschraml** [wlcrs/huawei_solar#820] opened 2024-10-11 20:12 UTC
### Describe your feature request

Update Huawei integration 

POWER_VOLT_AMPERE_REACTIVE was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'huawei_solar' custom integration

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment] 2024-10-14 06:28
Duplicate of #800

**Closed by wlcrs** 2024-10-14 06:28 UTC
