### ISSUE TITLE
[Bug]: Upgrade to v1.2.7 did not help - same bug still present.

### ISSUE THREAD

**Issue by mbuchber** [wlcrs/huawei_solar#492] opened 2023-09-30 17:03 UTC
### Describe the issue

Upgrade to v1.2.7 did not help - same bug still present.
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 178, in create
await huawei_solar._initialize()
File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 107, in _initialize
self.time_zone = (await self.get(rn.TIME_ZONE)).value
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 241, in get
return (await self.get_multiple([name], slave))[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 278, in get_multiple
decoder = BinaryPayloadDecoder.fromRegisters(response.registers, byteorder=Endian.BIG, wordorder=Endian.BIG)
^^^^^^^^^^
AttributeError: type object 'Endian' has no attribute 'BIG'

### Bescribe your Huawei Solar Setup

Inverter Type:
Inverter Firmware version:
SDongle present: yes / no
Power meter present: three phase / single phase / no
Battery: LG RESU xxkWh / LUNA2000 xxkWh / None
Battery Firmware version:

### How do you connect to the inverter?

Please select your connection method

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 178, in create
    await huawei_solar._initialize()
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 107, in _initialize
    self.time_zone = (await self.get(rn.TIME_ZONE)).value
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 241, in get
    return (await self.get_multiple([name], slave))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 278, in get_multiple
    decoder = BinaryPayloadDecoder.fromRegisters(response.registers, byteorder=Endian.BIG, wordorder=Endian.BIG)
                                                                               ^^^^^^^^^^
AttributeError: type object 'Endian' has no attribute 'BIG'
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment] 2023-09-30 17:52
Duplicate of #470. 

Please read https://github.com/wlcrs/huawei_solar/issues/470#issuecomment-1727258019 . I cannot help you with a dependency issue in your HA. The integration specifies the correct version for pyModbus in each release. 

Please be considerate, I'm doing this free of charge. If you keep spamming the issue tracker with this same issue, I will block you from interacting with it.

**Closed by wlcrs** 2023-09-30 17:52 UTC
Labels: bug
