### ISSUE TITLE
[Bug]: Inverter Daily yield wrong data

### ISSUE THREAD

**Issue by etamtlosz** [wlcrs/huawei_solar#446] opened 2023-08-15 08:44 UTC
### Describe the issue

The Inverter Daily yield is showing wrong data, could be function/calculation issue.
After it gets reset to 0 at midnight, immediately starts counting up. It looks like it adds the self consumption or something else to the daily yield. Given this behavior, the energy dashboard is showing weird graphs as well.

Screenshots:

Inverter Daily yield
![2023-08-15-20-26-09RfeXtvWAOo](https://github.com/wlcrs/huawei_solar/assets/7436784/77e61a34-4037-4d2b-a5af-518526419609)

HA energy dashboard
![2023-08-15-20-38-213H5pMsa90W](https://github.com/wlcrs/huawei_solar/assets/7436784/ce65429d-02ea-4f70-8f7e-ebe023a4925c)

Fusionsolar
![2023-08-15-20-39-20hFFJ6yhi9s](https://github.com/wlcrs/huawei_solar/assets/7436784/af52f16d-c82e-46b2-bc09-66dfdaaea0fc)

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-5KTL-L1
Inverter Firmware version: V200R001C00SPC130
SDongle present: yes
Power meter present: single phase
Battery: LUNA2000 10kWh
Battery Firmware version: V100R002C00SPC119 

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-48a88cee16ea14982dbd4d0c11ec880c.json.txt](https://github.com/wlcrs/huawei_solar/files/12342473/config_entry-huawei_solar-48a88cee16ea14982dbd4d0c11ec880c.json.txt)

### Upload your relevant debug logs

```text
I did not upload `Relevant debug logs` since I can't find anything related to it. It could be a calculation/formula issue.
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment] 2023-08-15 09:01
Duplicate of #1

**Closed by wlcrs** 2023-08-15 09:01 UTC
Labels: bug
