### ISSUE TITLE
[Feature Request]: Battery heath check info

### ISSUE THREAD

**Issue by jodewee** [wlcrs/huawei_solar#848] opened 2024-11-12 08:16 UTC
### Describe your feature request

Is it maybe possible to get the battery health check info in the integration?
When a battery does the check, it is not visible in one of the existing sensors.

![image](https://github.com/user-attachments/assets/b02e1af4-9bec-4078-9601-3e2629f232a4)

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment] 2024-11-25 10:37
Duplicate of #834

**Closed by wlcrs** 2024-11-25 10:37 UTC
