### ISSUE TITLE
[Bug]: Error occurred loading flow for integration huawei_solar

### ISSUE THREAD

**Issue by brambonsen** [wlcrs/huawei_solar#416] opened 2023-07-14 13:13 UTC
### Describe the issue

When I try to add the integration to Home Assistant, it comes back with an error:
2023-07-14 15:00:52.805 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration huawei_solar: cannot import name 'make_byte_string' from 'pymodbus.utilities' (/usr/local/lib/python3.11/site-packages/pymodbus/utilities.py)

I don't even get to the stage of connecting to the device or anything like that. It won't start or load.

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-4ktl
Inverter Firmware version:
SDongle present: yes 
Power meter present: three phase
Battery: None
Battery Firmware version:

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
2023-07-14 14:46:38.607 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration huawei_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-14 14:46:38.613 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-14 14:59:23.643 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration huawei_solar: cannot import name 'make_byte_string' from 'pymodbus.utilities' (/usr/local/lib/python3.11/site-packages/pymodbus/utilities.py)
2023-07-14 15:00:52.805 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration huawei_solar: cannot import name 'make_byte_string' from 'pymodbus.utilities' (/usr/local/lib/python3.11/site-packages/pymodbus/utilities.py)
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment] 2023-07-19 11:21
Duplicate of #408

**Closed by wlcrs** 2023-07-19 11:21 UTC
Labels: bug
