### ISSUE TITLE
[Bug]: change of units of measure - deprecated constant

### ISSUE THREAD

**Issue by forgo111** [wlcrs/huawei_solar#618] opened 2024-02-10 16:07 UTC
### Describe the issue

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 16:52:34 (3 occurrences)
Last logged: 16:52:34

ENERGY_KILO_WATT_HOUR was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues
POWER_WATT was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-5KTL-M1GIN300-5KTL-M1
Inverter Firmware version: V100R001C00SPC158
SDongle present: yes
Power meter present: three phase 
Battery:  / None

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

[config_entry-huawei_solar-7a8d809078c00388a3073e8afedf35b2.json](https://github.com/wlcrs/huawei_solar/files/14229760/config_entry-huawei_solar-7a8d809078c00388a3073e8afedf35b2.json)
Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
debugging not making sense, right?
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by forgo111** [comment] 2024-02-10 16:08
debugging:
2024-02-10 16:51:53.996 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-10 16:51:53.997 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration huawei_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-10 16:52:07.301 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2024-02-10 16:52:07.715 WARNING (MainThread) [homeassistant.setup] Setup of bluetooth is taking over 10 seconds.
2024-02-10 16:52:15.241 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2024-02-10 16:52:34.848 WARNING (MainThread) [homeassistant.const] ENERGY_KILO_WATT_HOUR was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues
2024-02-10 16:52:34.855 WARNING (MainThread) [homeassistant.const] POWER_WATT was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues
2024-02-10 16:52:34.912 WARNING (MainThread) [homeassistant.const] POWER_WATT was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues
2024-02-10 17:06:40.001 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064 with length 52 from slave 1
2024-02-10 17:06:40.002 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x95 0x0 0x0 0x0 0x6 0x1 0x3 0x7d 0x40 0x0 0x34
2024-02-10 17:06:40.003 DEBUG (MainThread) [pymodbus.logging] Adding transaction 149
2024-02-10 17:06:40.845 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x95 0x0 0x0 0x0 0x6b 0x1 0x3 0x68 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x9 0xf0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0x0 0x0 0xb 0xb8 0xa0 0x0 0x0 0x0 0x65 0xc7 0x27 0x80 0x65 0xc7 0xa9 0x9 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x2 0xf6 0x7d 0x0 0x3 0xd 0xfd 0x65 0xc7 0xad 0x1f 0x0 0x0 0x0 0x0 0x0 0x0 0x1 0xa1 old_data:  addr=None
2024-02-10 17:06:40.846 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x95 0x0 0x0 0x0 0x6b 0x1 0x3 0x68 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x9 0xf0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0x0 0x0 0xb 0xb8 0xa0 0x0 0x0 0x0 0x65 0xc7 0x27 0x80 0x65 0xc7 0xa9 0x9 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x2 0xf6 0x7d 0x0 0x3 0xd 0xfd 0x65 0xc7 0xad 0x1f 0x0 0x0 0x0 0x0 0x0 0x0 0x1 0xa1
2024-02-10 17:06:40.846 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2024-02-10 17:06:40.847 DEBUG (MainThread) [pymodbus.logging] Getting transaction 149
2024-02-10 17:06:40.848 DEBUG (MainThread) [pymodbus.logging] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2544, 0, 0, 0, 0, 0, 0, 65535, 0, 3000, 40960, 0, 26055, 10112, 26055, 43273, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 63101, 3, 3581, 26055, 44319, 0, 0, 0, 417]
2024-02-10 17:06:40.848 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:06:40.849 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:06:40.849 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:06:40.850 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:06:40.850 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\t\xf0']
2024-02-10 17:06:40.850 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:06:40.851 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:06:40.851 DEBUG (MainThread) [pymodbus.logging] handle: [b'e\xc7', b"'\x80"]
2024-02-10 17:06:40.852 DEBUG (MainThread) [pymodbus.logging] handle: [b'e\xc7', b'\xa9\t']
2024-02-10 17:06:40.852 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x02', b'\xf6}']
2024-02-10 17:06:40.853 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x01\xa1']
2024-02-10 17:06:40.907 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000 with length 20 from slave 1
2024-02-10 17:06:40.908 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x96 0x0 0x0 0x0 0x6 0x1 0x3 0x7d 0x0 0x0 0x14
2024-02-10 17:06:40.910 DEBUG (MainThread) [pymodbus.logging] Adding transaction 150
2024-02-10 17:06:41.553 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x96 0x0 0x0 0x0 0x2b 0x1 0x3 0x28 0x0 0x1 0x0 0x0 0x0 0x4 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xa8 0xaf 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 old_data:  addr=None
2024-02-10 17:06:41.553 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x96 0x0 0x0 0x0 0x2b 0x1 0x3 0x28 0x0 0x1 0x0 0x0 0x0 0x4 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xa8 0xaf 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
2024-02-10 17:06:41.554 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2024-02-10 17:06:41.554 DEBUG (MainThread) [pymodbus.logging] Getting transaction 150
2024-02-10 17:06:41.555 DEBUG (MainThread) [pymodbus.logging] [1, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43183, 0, 0, 0, 0]
2024-02-10 17:06:41.555 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:06:41.608 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37201 with length 1 from slave 1
2024-02-10 17:06:41.609 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x97 0x0 0x0 0x0 0x6 0x1 0x3 0x91 0x51 0x0 0x1
2024-02-10 17:06:41.611 DEBUG (MainThread) [pymodbus.logging] Adding transaction 151
2024-02-10 17:06:42.384 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x97 0x0 0x0 0x0 0x5 0x1 0x3 0x2 0x0 0x0 old_data:  addr=None
2024-02-10 17:06:42.385 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x97 0x0 0x0 0x0 0x5 0x1 0x3 0x2 0x0 0x0
2024-02-10 17:06:42.385 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2024-02-10 17:06:42.385 DEBUG (MainThread) [pymodbus.logging] Getting transaction 151
2024-02-10 17:06:42.387 DEBUG (MainThread) [pymodbus.logging] [0]
2024-02-10 17:06:42.440 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37100 with length 38 from slave 1
2024-02-10 17:06:42.441 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x98 0x0 0x0 0x0 0x6 0x1 0x3 0x90 0xec 0x0 0x26
2024-02-10 17:06:42.443 DEBUG (MainThread) [pymodbus.logging] Adding transaction 152
2024-02-10 17:06:43.090 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x98 0x0 0x0 0x0 0x4f 0x1 0x3 0x4c 0x0 0x1 0x0 0x0 0x8 0xf7 0x0 0x0 0x9 0x4 0x0 0x0 0x8 0xfd 0xff 0xff 0xff 0x22 0xff 0xff 0xff 0x32 0xff 0xff 0xfe 0xca 0xff 0xff 0xfa 0x0 0x0 0x0 0x1 0xdd 0xfc 0x7b 0x13 0x88 0x0 0x2 0x6b 0xe5 0x0 0x2 0xec 0x8f 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0 0xf 0x93 0x0 0x0 0xf 0x98 0x0 0x0 0xf 0x8c 0xff 0xff 0xfe 0x4c 0xff 0xff 0xfe 0x63 0xff 0xff 0xfd 0x51 old_data:  addr=None
2024-02-10 17:06:43.091 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x98 0x0 0x0 0x0 0x4f 0x1 0x3 0x4c 0x0 0x1 0x0 0x0 0x8 0xf7 0x0 0x0 0x9 0x4 0x0 0x0 0x8 0xfd 0xff 0xff 0xff 0x22 0xff 0xff 0xff 0x32 0xff 0xff 0xfe 0xca 0xff 0xff 0xfa 0x0 0x0 0x0 0x1 0xdd 0xfc 0x7b 0x13 0x88 0x0 0x2 0x6b 0xe5 0x0 0x2 0xec 0x8f 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0 0xf 0x93 0x0 0x0 0xf 0x98 0x0 0x0 0xf 0x8c 0xff 0xff 0xfe 0x4c 0xff 0xff 0xfe 0x63 0xff 0xff 0xfd 0x51
2024-02-10 17:06:43.091 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2024-02-10 17:06:43.092 DEBUG (MainThread) [pymodbus.logging] Getting transaction 152
2024-02-10 17:06:43.093 DEBUG (MainThread) [pymodbus.logging] [1, 0, 2295, 0, 2308, 0, 2301, 65535, 65314, 65535, 65330, 65535, 65226, 65535, 64000, 0, 477, 64635, 5000, 2, 27621, 2, 60559, 0, 0, 1, 0, 3987, 0, 3992, 0, 3980, 65535, 65100, 65535, 65123, 65535, 64849]
2024-02-10 17:06:43.093 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x08\xf7']
2024-02-10 17:06:43.093 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\t\x04']
2024-02-10 17:06:43.094 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x08\xfd']
2024-02-10 17:06:43.094 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xff"']
2024-02-10 17:06:43.094 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xff2']
2024-02-10 17:06:43.095 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfe\xca']
2024-02-10 17:06:43.095 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfa\x00']
2024-02-10 17:06:43.095 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x01\xdd']
2024-02-10 17:06:43.096 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x02', b'k\xe5']
2024-02-10 17:06:43.096 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x02', b'\xec\x8f']
2024-02-10 17:06:43.096 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:06:43.097 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x0f\x93']
2024-02-10 17:06:43.097 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x0f\x98']
2024-02-10 17:06:43.097 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x0f\x8c']
2024-02-10 17:06:43.099 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfeL']
2024-02-10 17:06:43.099 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfec']
2024-02-10 17:06:43.100 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfdQ']
2024-02-10 17:06:43.100 DEBUG (MainThread) [custom_components.huawei_solar] Finished fetching TA2260065924_data_update_coordinator data in 3.100 seconds (success: True)
2024-02-10 17:07:13.002 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064 with length 52 from slave 1
2024-02-10 17:07:13.003 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x99 0x0 0x0 0x0 0x6 0x1 0x3 0x7d 0x40 0x0 0x34
2024-02-10 17:07:13.004 DEBUG (MainThread) [pymodbus.logging] Adding transaction 153
2024-02-10 17:07:13.218 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x99 0x0 0x0 0x0 0x6b 0x1 0x3 0x68 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x9 0xf0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0x0 0x0 0xb 0xb8 0xa0 0x0 0x0 0x0 0x65 0xc7 0x27 0x80 0x65 0xc7 0xa9 0x9 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x2 0xf6 0x7d 0x0 0x3 0xd 0xfd 0x65 0xc7 0xad 0x3e 0x0 0x0 0x0 0x0 0x0 0x0 0x1 0xa1 old_data:  addr=None
2024-02-10 17:07:13.219 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x99 0x0 0x0 0x0 0x6b 0x1 0x3 0x68 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x9 0xf0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0x0 0x0 0xb 0xb8 0xa0 0x0 0x0 0x0 0x65 0xc7 0x27 0x80 0x65 0xc7 0xa9 0x9 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x2 0xf6 0x7d 0x0 0x3 0xd 0xfd 0x65 0xc7 0xad 0x3e 0x0 0x0 0x0 0x0 0x0 0x0 0x1 0xa1
2024-02-10 17:07:13.219 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2024-02-10 17:07:13.220 DEBUG (MainThread) [pymodbus.logging] Getting transaction 153
2024-02-10 17:07:13.221 DEBUG (MainThread) [pymodbus.logging] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2544, 0, 0, 0, 0, 0, 0, 65535, 0, 3000, 40960, 0, 26055, 10112, 26055, 43273, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 63101, 3, 3581, 26055, 44350, 0, 0, 0, 417]
2024-02-10 17:07:13.221 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:07:13.222 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:07:13.222 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:07:13.223 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:07:13.223 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\t\xf0']
2024-02-10 17:07:13.223 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:07:13.224 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:07:13.224 DEBUG (MainThread) [pymodbus.logging] handle: [b'e\xc7', b"'\x80"]
2024-02-10 17:07:13.224 DEBUG (MainThread) [pymodbus.logging] handle: [b'e\xc7', b'\xa9\t']
2024-02-10 17:07:13.225 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x02', b'\xf6}']
2024-02-10 17:07:13.225 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x01\xa1']
2024-02-10 17:07:13.279 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000 with length 20 from slave 1
2024-02-10 17:07:13.280 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x9a 0x0 0x0 0x0 0x6 0x1 0x3 0x7d 0x0 0x0 0x14
2024-02-10 17:07:13.282 DEBUG (MainThread) [pymodbus.logging] Adding transaction 154
2024-02-10 17:07:14.008 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x9a 0x0 0x0 0x0 0x2b 0x1 0x3 0x28 0x0 0x1 0x0 0x0 0x0 0x4 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xa8 0xaf 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 old_data:  addr=None
2024-02-10 17:07:14.009 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x9a 0x0 0x0 0x0 0x2b 0x1 0x3 0x28 0x0 0x1 0x0 0x0 0x0 0x4 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xa8 0xaf 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
2024-02-10 17:07:14.009 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2024-02-10 17:07:14.009 DEBUG (MainThread) [pymodbus.logging] Getting transaction 154
2024-02-10 17:07:14.010 DEBUG (MainThread) [pymodbus.logging] [1, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43183, 0, 0, 0, 0]
2024-02-10 17:07:14.011 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:07:14.064 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37201 with length 1 from slave 1
2024-02-10 17:07:14.064 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x9b 0x0 0x0 0x0 0x6 0x1 0x3 0x91 0x51 0x0 0x1
2024-02-10 17:07:14.066 DEBUG (MainThread) [pymodbus.logging] Adding transaction 155
2024-02-10 17:07:14.859 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x9b 0x0 0x0 0x0 0x5 0x1 0x3 0x2 0x0 0x0 old_data:  addr=None
2024-02-10 17:07:14.859 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x9b 0x0 0x0 0x0 0x5 0x1 0x3 0x2 0x0 0x0
2024-02-10 17:07:14.860 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2024-02-10 17:07:14.860 DEBUG (MainThread) [pymodbus.logging] Getting transaction 155
2024-02-10 17:07:14.861 DEBUG (MainThread) [pymodbus.logging] [0]
2024-02-10 17:07:14.914 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37100 with length 38 from slave 1
2024-02-10 17:07:14.915 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x9c 0x0 0x0 0x0 0x6 0x1 0x3 0x90 0xec 0x0 0x26
2024-02-10 17:07:14.917 DEBUG (MainThread) [pymodbus.logging] Adding transaction 156
2024-02-10 17:07:15.798 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x9c 0x0 0x0 0x0 0x4f 0x1 0x3 0x4c 0x0 0x1 0x0 0x0 0x8 0xfa 0x0 0x0 0x9 0x4 0x0 0x0 0x8 0xfa 0xff 0xff 0xff 0x22 0xff 0xff 0xff 0x32 0xff 0xff 0xfe 0xcc 0xff 0xff 0xfa 0x4 0x0 0x0 0x1 0xdf 0xfc 0x7b 0x13 0x88 0x0 0x2 0x6b 0xe5 0x0 0x2 0xec 0x91 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0 0xf 0x94 0x0 0x0 0xf 0x94 0x0 0x0 0xf 0x8d 0xff 0xff 0xfe 0x4d 0xff 0xff 0xfe 0x63 0xff 0xff 0xfd 0x54 old_data:  addr=None
2024-02-10 17:07:15.799 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x9c 0x0 0x0 0x0 0x4f 0x1 0x3 0x4c 0x0 0x1 0x0 0x0 0x8 0xfa 0x0 0x0 0x9 0x4 0x0 0x0 0x8 0xfa 0xff 0xff 0xff 0x22 0xff 0xff 0xff 0x32 0xff 0xff 0xfe 0xcc 0xff 0xff 0xfa 0x4 0x0 0x0 0x1 0xdf 0xfc 0x7b 0x13 0x88 0x0 0x2 0x6b 0xe5 0x0 0x2 0xec 0x91 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0 0xf 0x94 0x0 0x0 0xf 0x94 0x0 0x0 0xf 0x8d 0xff 0xff 0xfe 0x4d 0xff 0xff 0xfe 0x63 0xff 0xff 0xfd 0x54
2024-02-10 17:07:15.799 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2024-02-10 17:07:15.800 DEBUG (MainThread) [pymodbus.logging] Getting transaction 156
2024-02-10 17:07:15.801 DEBUG (MainThread) [pymodbus.logging] [1, 0, 2298, 0, 2308, 0, 2298, 65535, 65314, 65535, 65330, 65535, 65228, 65535, 64004, 0, 479, 64635, 5000, 2, 27621, 2, 60561, 0, 0, 1, 0, 3988, 0, 3988, 0, 3981, 65535, 65101, 65535, 65123, 65535, 64852]
2024-02-10 17:07:15.801 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x08\xfa']
2024-02-10 17:07:15.802 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\t\x04']
2024-02-10 17:07:15.802 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x08\xfa']
2024-02-10 17:07:15.802 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xff"']
2024-02-10 17:07:15.803 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xff2']
2024-02-10 17:07:15.803 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfe\xcc']
2024-02-10 17:07:15.803 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfa\x04']
2024-02-10 17:07:15.804 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x01\xdf']
2024-02-10 17:07:15.804 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x02', b'k\xe5']
2024-02-10 17:07:15.804 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x02', b'\xec\x91']
2024-02-10 17:07:15.805 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2024-02-10 17:07:15.805 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x0f\x94']
2024-02-10 17:07:15.805 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x0f\x94']
2024-02-10 17:07:15.807 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x0f\x8d']
2024-02-10 17:07:15.808 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfeM']
2024-02-10 17:07:15.808 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfec']
2024-02-10 17:07:15.808 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfdT']
2024-02-10 17:07:15.809 DEBUG (MainThread) [custom_components.huawei_solar] Finished fetching TA2260065924_data_update_coordinator data in 2.808 seconds (success: True)

**Comment by Roving-Ronin** [comment] 2024-02-12 01:59
Please check to see if an issue has already been opened. This one is already logged, see: https://github.com/wlcrs/huawei_solar/issues/583

**Comment by forgo111** [comment] 2024-02-12 14:20
sorry

 

Von: Roving Ronin ***@***.***> 
Gesendet: Montag, 12. Februar 2024 03:00
An: wlcrs/huawei_solar ***@***.***>
Cc: forgo111 ***@***.***>; Author ***@***.***>
Betreff: Re: [wlcrs/huawei_solar] [Bug]: change of units of measure - deprecated constant (Issue #618)

 

Please check to see if an issue has already been opened. This one is already logged, see: #583 <https://github.com/wlcrs/huawei_solar/issues/583>

**Comment by wlcrs** [comment] 2024-02-24 09:00
Duplicate of #583

**Closed by wlcrs** 2024-02-24 09:00 UTC
Labels: bug
