### ISSUE TITLE
[Bug]: Yield in dashboard showing incorrectly

### ISSUE THREAD

**Issue by ripcam21** [wlcrs/huawei_solar#561] opened 2023-12-20 14:56 UTC
### Describe the issue

It appears the daily or total yield energy sensors is inaccurately showing yield.  It shows yield for all hours of the day.  It also appears to be calculating lower yield during the day and not registering the full output during the hour.
![error](https://github.com/wlcrs/huawei_solar/assets/106219466/60d93e03-0275-4bdb-8a08-c614d5aa5bfb)

### Bescribe your Huawei Solar Setup

Inverter Type:
Inverter Firmware version:
SDongle present: yes / no
Power meter present: three phase / single phase / no
Battery: LG RESU xxkWh / LUNA2000 xxkWh / None
Battery Firmware version:

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-76b11c4db9f0d504a6c067e704b4d125.json (1).txt](https://github.com/wlcrs/huawei_solar/files/13728771/config_entry-huawei_solar-76b11c4db9f0d504a6c067e704b4d125.json.1.txt)

### Upload your relevant debug logs

```text
N/A
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [ ] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment] 2023-12-20 15:36
Duplicate of #1

**Closed by wlcrs** 2023-12-20 15:36 UTC
Labels: bug
