### ISSUE TITLE
[Bug]: Value sais "not available anymore" ("nicht mehr verfügbar" in german)

### ISSUE THREAD

**Issue by lomtaslipptas** [wlcrs/huawei_solar#556] opened 2023-12-14 19:52 UTC
### Describe the issue

Okay, my situation is a bit tricky perhaps, but hopefully we find a solution for that.

I have the huawei components for one year now. At the beginning I red all the values via RedNode directly to iobroker. After some time I decided to integrate evcc for putting the energy in the vehicle when it is available. While evcc and RedNode wanted to collect both the information from the inverter via Modbus the values where not really stable. There were a lot of timeout issues and so on. So I used the modbus-proxy from evcc. That means evcc is talking with the inverter directly and iobroker is asking evcc to collect the values. Evcc is ensuring that there is no collision. 

Now I am trying to go from iobroker to home assistant. The values from the inverter a quite essential for a lot of use cases. I thought it should be able to use the modbus-proxy from evcc for home assistant too. But with the huawei_solar plugin I habe a very uncommon behaviour: The values are available sometimes, but are changing constantly to "not available anymore" which is "nicht mehr verfügbar" in german. All other tools (evcc and iobroker) showing correct values all the time.

Here you can see the logbuch from one entity to get an impression of this behaviour:
```
Battery Status nicht mehr verfügbar
20:25:37 - Vor 8 Minuten
Battery Status wechselte zu Running
20:24:48 - Vor 9 Minuten
Battery Status nicht mehr verfügbar
20:20:47 - Vor 13 Minuten
Battery Status wechselte zu Running
20:19:58 - Vor 14 Minuten
Battery Status nicht mehr verfügbar
20:17:34 - Vor 16 Minuten
Battery Status wechselte zu Running
20:16:44 - Vor 17 Minuten
Battery Status nicht mehr verfügbar
20:04:28 - Vor 29 Minuten
Battery Status wechselte zu Running
20:03:39 - Vor 30 Minuten
Battery Status nicht mehr verfügbar
19:51:20 - Vor 43 Minuten
Battery Status wechselte zu Running
19:50:45 - Vor 43 Minuten
Battery Status nicht mehr verfügbar
19:50:00 - Vor 44 Minuten
Battery Status wechselte zu Running
19:49:10 - Vor 45 Minuten
Battery Status nicht mehr verfügbar
19:48:28 - Vor 1 Stunde
Battery Status wechselte zu Running
19:47:39 - Vor 1 Stunde
Battery Status nicht mehr verfügbar
19:46:50 - Vor 1 Stunde
```
As you can see: The correct status can be read, but is only available for some seconds (less than a minute) and goes back to not available any more for some minutes. Than it toggles force and back again.

I am really open to change my network setup for any option to have the modbus proxy inside of home assistant if this option will solve my problem. Or if you have any other hint which could be helpful let me know.

The protocoll shows a timeout error:
<img width="403" alt="image" src="https://github.com/wlcrs/huawei_solar/assets/3419533/02f04a15-b46b-4741-8427-be2a9cc6eb13">

Perhaps it is relevant to know that the Port for the Modbus Proxy is not 502 but 5200. Evcc than translates this into 502.

Keep in mind: I am very new to home assistant, love it, but have to learn a lot. Any help is very much appreciated. Thank you.

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1
Inverter Firmware version: V100R001C00SPC153
SDongle present: yes
Power meter present: three phase
Battery: LUNA2000 5kWh
Battery Firmware version: V100R002C00SPC118 

### How do you connect to the inverter?

Please select your connection method

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-7e34cfd1af9a8ca439fbaa464e7e7971.json (4).txt](https://github.com/wlcrs/huawei_solar/files/13677514/config_entry-huawei_solar-7e34cfd1af9a8ca439fbaa464e7e7971.json.4.txt)
[home-assistant_huawei_solar_2023-12-14T19-47-22.874Z.log](https://github.com/wlcrs/huawei_solar/files/13677575/home-assistant_huawei_solar_2023-12-14T19-47-22.874Z.log)

### Upload your relevant debug logs

```text
see above
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by lomtaslipptas** [comment] 2023-12-14 19:57
In the log from evcc I can find this: 
<img width="845" alt="image" src="https://github.com/wlcrs/huawei_solar/assets/3419533/f9d34501-1d19-4ed1-986f-000d8f0f6160">

Additional information: HA is running in a docker container inside of a Synology NAS on the host network.

**Comment by wlcrs** [comment] 2023-12-18 13:53
This issue seems to be caused by an unstable connection to the inverter. This integration already has already implemented a lot of logic to automatically recover from unstable connections. The two most important ones are:
- each Modbus request is retried for up to 6 times, with increasing waits between each attempt to allow the connection to recover;
- after 3 failed Modbus requests the connection is reset to fix hanging connections.

Please understand that I cannot help you solve your unstable connection. Consider [an alternative connection method](https://github.com/wlcrs/huawei_solar/wiki/Connecting-to-the-inverter).
If you are convinced that there is no connectivity issue, then I invite you to debug and fix the problem yourself and submit a pull request to the underlying [huawei-solar Python library](https://gitlab.com/Emilv2/huawei-solar). Your input would be greatly appreciated.

As there is nothing actionable for me to do in this issue, I'm closing it. You are welcome to open a topic in [Discussions: Connecting to the inverter](https://github.com/wlcrs/huawei_solar/discussions/categories/connecting-to-the-inverter) to get community support for your problem.

**Closed by wlcrs** 2023-12-18 13:53 UTC
Labels: bug
