### ISSUE TITLE
[Bug]:  Power meter not showing in HA

### ISSUE THREAD

**Issue by AlfaCube** [wlcrs/huawei_solar#588] opened 2024-01-12 15:13 UTC
### Describe the issue

Few days ago my Huawei solar stopped working.
Here is the error:

This error originated from a custom integration.
Logger: pymodbus.logging
Source: custom_components/huawei_solar/init.py:92
Integration: Huawei Solar (documentation, issues)
First occurred: 12:34:58 AM (11 occurrences)
Last logged: 12:46:10 AM

Failed to connect [Errno 111] Connect call failed.

Restarded the invertors, restarted the HA, the wifi. deleted the Huawei Solar from HA.
Now I see only the invertor. I cant see the Power Meter.
The ModBus is enabled.
Sdongle dissapierded from my wifi list and now after the reboot has come back.
The Sdongle has the latest update.

Can you gus help me?

### Bescribe your Huawei Solar Setup

Inverter Type:
Inverter Firmware version:
SDongle present: yes / no
Power meter present: three phase / single phase / no
Battery: LG RESU xxkWh / LUNA2000 xxkWh / None
Battery Firmware version:

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[home-assistant_huawei_solar_2024-01-12T15-04-48.815Z.log](https://github.com/wlcrs/huawei_solar/files/13920585/home-assistant_huawei_solar_2024-01-12T15-04-48.815Z.log)

### Upload your relevant debug logs

```text
This error originated from a custom integration.

Logger: custom_components.huawei_solar
Source: helpers/update_coordinator.py:306
Integration: Huawei Solar (documentation, issues)
First occurred: 2:57:34 PM (2 occurrences)
Last logged: 3:39:18 PM

Timeout fetching TA2240030061_data_update_coordinator data
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment] 2024-01-12 15:44
This issue seems to be caused by a connection failure or an unstable connection to the inverter. This integration already has already implemented a lot of logic to automatically recover from connection failures or unstable connections. The three most important ones are:
- automatic reconnects if the connection to the inverter failed;
- each Modbus request is retried for up to 6 times, with increasing waits between each attempt to allow the connection to recover;
- after 3 failed Modbus requests the connection is reset to fix hanging connections.

Please understand that I cannot help you solve your connection failure or unstable connection. Consider [an alternative connection method](https://github.com/wlcrs/huawei_solar/wiki/Connecting-to-the-inverter).
If you are convinced that there is no connectivity issue, then I invite you to debug and fix the problem yourself and submit a pull request to the underlying [huawei-solar Python library](https://gitlab.com/Emilv2/huawei-solar). Your input would be greatly appreciated.

As there is nothing actionable for me to do in this issue, I'm closing it. You are welcome to open a topic in [Discussions: Connecting to the inverter](https://github.com/wlcrs/huawei_solar/discussions/categories/connecting-to-the-inverter) to get community support for your problem.

**Closed by wlcrs** 2024-01-12 15:44 UTC
Labels: bug
