### ISSUE TITLE
[Bug]: Incorrect Total yield/day 

### ISSUE THREAD

**Issue by wavelov3r** [wlcrs/huawei_solar#666] opened 2024-03-29 17:39 UTC
### Describe the issue

The total yield energy  take in account only inverted energy, not the total (home battery recharge is excluded)

![IMG_20240329_183134](https://github.com/wlcrs/huawei_solar/assets/104383649/b3974f6c-4988-466f-984d-ccb3ad75384b)
![IMG_20240329_183216](https://github.com/wlcrs/huawei_solar/assets/104383649/998fc598-00fe-4d31-8b64-d24d18d9bef1)

### Bescribe your Huawei Solar Setup

Inverter Type: 6ktl-l1
Inverter Firmware version: last
SDongle present:  no
Power meter present: single phase 
Battery: LUNA2000 15kWh / None
Battery Firmware version: last

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
No needs for logs
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment] 2024-03-29 19:25
Duplicate of #1

**Closed by wlcrs** 2024-03-29 19:25 UTC
Labels: bug

**Comment by wavelov3r** [comment] 2024-03-30 19:08
I have set nothing. Also i've noticed time ago this bug, but i was thinking it was resolved with last release.

Today this is the result, repeat, no settings moved.


![IMG_20240330_200530](https://github.com/wlcrs/huawei_solar/assets/104383649/ee5504bb-6286-4746-9c63-b7055cb28da0)
![IMG_20240330_200606](https://github.com/wlcrs/huawei_solar/assets/104383649/bfbad9d4-f5b2-4a8d-b7a1-0269cb4078fc)
