### ISSUE TITLE
config flow could not be loaded 

### ISSUE THREAD

**Issue by Ryuu125** [wlcrs/huawei_solar#12] opened 2022-01-07 04:25 UTC
After installing Huawei Solar i cannot get past the config flow could not be loaded warning message, I have checked the closed issue in #4 and i have python version 3.9.7 installing on a Hyper V system using HA 2021.12.8
![image](https://user-images.githubusercontent.com/97264891/148491323-5aec8f43-acf2-438e-8f76-a64cc1b6e051.png)

The only error that does come up is this
Logger: homeassistant.config_entries
Source: config_entries.py:720
First occurred: 12:24:27 PM (1 occurrences)
Last logged: 12:24:27 PM

Error occurred loading configuration flow for integration huawei_solar: cannot import name 'AsyncHuaweiSolar' from 'huawei_solar' (/usr/local/lib/python3.9/site-packages/huawei_solar/__init__.py)

**Comment by wlcrs** [comment] 2022-01-07 07:57
Hi, this error indicates that the dependency for package `huawei-solar==1.2.0` specified in `manifest.json` (here: https://github.com/wlcrs/huawei_solar/blob/main/manifest.json#L7) was not installed correctly. Because of that, the class `AsyncHuaweiSolar` is missing. I checked pypi, and the package `huawei-solar` is still published, so the issue must be on your side.

Can you try a full reinstall (by removing the folder from custom_components, restarting HA, adding the integration again, restarting again) to check if you can find any relevant information on why the installation of that dependency failed? You should find some indications in the logs after restarting HA when you added the custom_component again.

**Comment by Ryuu125** [comment] 2022-01-07 08:24
Hi there
Yeah doing a full reinstall like removing it from the components section completely and reinstalling it again has not changed anything. The logs arent completely showing anything for why it failed besides the same error log.

**Comment by wlcrs** [comment] 2022-01-07 17:27
I tested the latest release in a clean Home Assistant installation less than two weeks ago. If your Home Assistant installation doesn't properly install dependencies defined in the `manifest.json` file, then I'm afraid you'll need to investigate that further.

I'm closing this issue as it is an issue with your HA installation, and not caused by an error in this integration.

**Closed by wlcrs** 2022-01-07 17:27 UTC

**Comment by gieljnssns** [comment] 2022-01-21 13:54
I have a similar error
```
Logger: homeassistant.config_entries
Source: config_entries.py:720
First occurred: 14:33:11 (1 occurrences)
Last logged: 14:33:11

Error occurred loading configuration flow for integration huawei_solar: cannot import name 'is_installed' from 'pymodbus.compat' (/usr/local/lib/python3.9/site-packages/pymodbus/compat.py)
```

<img width="570" alt="Schermafbeelding 2022-01-21 om 14 53 51" src="https://user-images.githubusercontent.com/17234951/150538791-143dd48f-b051-4004-8c10-aceadd7ff9e7.png">

**Comment by wlcrs** [comment] 2022-01-21 14:04
Please open your own issue, and fill in the template to provide me with the necessary information about your installation.
