### ISSUE TITLE
[Feature Request]: Battery temperature

### ISSUE THREAD

**Issue by julianbl** [wlcrs/huawei_solar#541] opened 2023-11-16 08:47 UTC
### Describe your feature request

Hi
Would it be possible to add the internal temperature reading of the battery?
here is the register information:

Signal  Name:  [Energy storage unit 1] battery temperature
Read/ Write: RO
Type: INT16
Unit : ℃
Gain: 10
Address: 37022
Quantity 1 

Subsequent battery modules:
Battery 2: Address: 37752 
other batteries values are only max a min, not actual temp.

Thank you!

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by wlcrs** [comment] 2023-11-19 09:52
Duplicate of #74 

If you're comfortable with Python, then you can add these sensors separately by following this guide: https://github.com/wlcrs/huawei_solar/wiki/Defining-custom-sensors

**Closed by wlcrs** 2023-11-19 09:52 UTC
